package com.emarsys.mobileengage.push

import com.emarsys.core.Mockable
import com.emarsys.mobileengage.api.push.NotificationInformationListener

@Mockable
class SilentNotificationInformationListenerProvider(var silentNotificationInformationListener: NotificationInformationListener?)