version: 2
updates:
  - package-ecosystem: "gradle"
    target-branch: "dev"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(dependabot)"
    open-pull-requests-limit: 5
  - package-ecosystem: "github-actions"
    target-branch: "dev"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(dependabot)"
    open-pull-requests-limit: 5