org.gradle.jvmargs=-Xmx4096m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.configureondemand=false
android.useAndroidX=true
org.gradle.parallel=true
org.gradle.vfs.watch=true
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false

#android.enableBuildConfigAsBytecode=true