@Library(['android-pipeline', 'general-pipeline']) _

node('master') {
    withSlack channel: 'jenkins', {
        timeout(20) {
            stage("init") {
                deleteDir()
                deviceCount shouldBe: env.ANDROID_DEVICE_COUNT, action: { devices, message ->
                    slackMessage channel: 'jenkins', text: message
                }

                git url: 'git@github.com:emartech/android-emarsys-sdk.git', branch: 'master'

                def javaTestFileCount = sh(returnStdout: true, script: 'find . -name  "*Test.java" | wc -l').trim() as Integer
                def kotlinTestFileCount = sh(returnStdout: true, script: 'find . -name  "*Test.kt" | wc -l').trim() as Integer
                def javaTimeoutRuleCount = sh(returnStdout: true, script: 'grep -r "^\\s*public TestRule timeout = TimeoutUtils.getTimeoutRule();" . | wc -l').trim() as Integer
                def kotlinTimeoutRuleCount = sh(returnStdout: true, script: 'grep -r "^\\s*val timeout: TestRule = TimeoutUtils.timeoutRule" . | wc -l').trim() as Integer

                if (javaTestFileCount != javaTimeoutRuleCount) {
                    error("$javaTestFileCount java tests found, but only $javaTimeoutRuleCount timeout rules!")
                }
                if (kotlinTestFileCount != kotlinTimeoutRuleCount) {
                    error("$javaTestFileCount kotlin tests found, but only $kotlinTimeoutRuleCount timeout rules!")
                }
            }

            stage("build") {
                androidBuild module: 'emarsys', andArchive: 'emarsys/**/*.aar'
            }

            stage('lint') {
                androidLint module: 'emarsys', andArchive: 'emarsys/**/lint-results*.*'
            }

            stage('remove-test-app') {
                sh './gradlew emarsys:uninstallDebugAndroidTest'
            }

            stage("instrumentation-test") {
                androidInstrumentationTest module: 'emarsys', withScreenOn: true, withLock: env.ANDROID_DEVICE_FARM_LOCK, runTrulyParallel: true, withStepNames: env.ANDROID_STEP_NAMES, andArchive: 'emarsys/**/outputs/androidTest-results/connected/*.xml'
            }
        }
    }
}
