@Library(['android-pipeline', 'general-pipeline']) _

node('master') {
    withSlack channel: 'jenkins', {
        timeout(20) {
            stage("init") {
                deleteDir()
                deviceCount shouldBe: env.ANDROID_DEVICE_COUNT, action: { devices, message ->
                    slackMessage channel: 'jenkins', text: message
                }

                git url: 'git@github.com:emartech/android-emarsys-sdk.git', branch: 'master'

                def testFileCount = sh(returnStdout: true, script: 'find . -name  "*Test.java" | wc -l').trim() as Integer
                def timeoutRuleCount = sh(returnStdout: true, script: 'grep -r "^\\s*public TestRule timeout = TimeoutUtils.getTimeoutRule();" . | wc -l').trim() as Integer
                if (testFileCount != timeoutRuleCount) {
                    error("$testFileCount tests found, but only $timeoutRuleCount timeout rules!")
                }
            }

            stage("build") {
                androidBuild module: 'mobile-engage-api', andArchive: 'mobile-engage-api/**/*.aar'
                androidBuild module: 'mobile-engage', andArchive: 'mobile-engage/**/*.aar'
            }

            stage('lint') {
                androidLint module: 'mobile-engage-api', andArchive: 'mobile-engage-api/**/lint-results*.*'
                androidLint module: 'mobile-engage', andArchive: 'mobile-engage/**/lint-results*.*'
            }

            stage('remove-test-app') {
                sh './gradlew mobile-engage-api:uninstallDebugAndroidTest'
                sh './gradlew mobile-engage:uninstallDebugAndroidTest'
            }

            stage("mobile-engage-api-cAT") {
                androidInstrumentationTest module: 'mobile-engage-api', withScreenOn: true, withLock: env.ANDROID_DEVICE_FARM_LOCK, runTrulyParallel: true, withStepNames: env.ANDROID_STEP_NAMES, andArchive: 'mobile-engage-api/**/outputs/androidTest-results/connected/*.xml'
            }

            stage("mobile-engage-cAT") {
                androidInstrumentationTest module: 'mobile-engage', withScreenOn: true, withLock: env.ANDROID_DEVICE_FARM_LOCK, runTrulyParallel: true, withStepNames: env.ANDROID_STEP_NAMES, andArchive: 'mobile-engage/**/outputs/androidTest-results/connected/*.xml'
            }
        }
    }
}